// Generated by CoffeeScript 1.6.2
var route;

route = {};

exports.on = function(key, callback) {
  return route[key] = callback;
};

exports.connect = function(domain, port) {
  var socket;

  if (port == null) {
    port = Number(domain);
    domain = location.hostname;
  }
  socket = new WebSocket("ws://" + domain + ":" + port);
  exports.emit = function(key, value) {
    return socket.send(JSON.stringify({
      key: key,
      value: value
    }));
  };
  socket.onmessage = function(event) {
    var data, _name;

    data = JSON.parse(event.data);
    return typeof route[_name = data.key] === "function" ? route[_name](data.value) : void 0;
  };
  exports.onopen = function(callback) {
    return socket.onopen = callback;
  };
  return exports;
};
