// Generated by CoffeeScript 1.6.2
var delay, ws;

delay = function(t, f) {
  return setTimeout(f, t);
};

ws = require("../lib/index");

ws.connect(3000);

ws.onopen(function() {
  return console.log("opened");
});

ws.on("greet", function(data) {
  return console.log(data);
});

ws.on("delay", function(data) {
  return console.log("delay", data);
});

console.log("start");

delay(1000, function() {
  return ws.emit("call", "from client");
});

ws.on("repeat", function(data) {
  ws.emit("repeat", data);
  return console.log("have data", data);
});
